---
title: "Compétition fiscale locale"
author: Vincent Robitaille
format: 
  revealjs:
    theme: dark
editor: visual
bibliography: references.bib
csl: apa.csl
---

## Pertinence


Financement des biens publics locaux

-   Routes municipales
-   Sécurité publique

Défis économiques et politiques
-   Érosion de l'assiette fiscale
-   "Spill over" d'externalités et de bénéfices
-   Satisfaction des électeurs

::: notes
**Biens/services publics**: routes, sécurité, parcs, aqueducs, entretient, loisirs, culture, éducation (partiel/variable)

**Défis**

**Érosion**: la base d'imposition peut se déplacer en fonction des décisions de taxation

**Spill over**: municipalité bénéficie ou souffrent des décisions de ses voisins (ex: déplacement de la criminalité)

**Satisfaction des électeurs**: yardstick competition

**Optimalité**: biens à fort spill over peuvent être sous financés (payeur ne récupère pas tous les bénéfices)
:::

## Cadre théorique

Modèles de compétitivité fiscale (concurrence parfaite)

-   [@tiebout1956]

Modèles de compétition fiscale avec interactions stratégiques (théorie des jeux)

## Compétition fiscale (Tiebout)

Compétition des juridictions pour offrir des combinaisons de taxes et biens publics locaux

-   Taxes sans distorsions
-   Taille faible des juridictions face à l'économie
-   Incapacité des juridictions à influencer le marché
-   Similaire aux modèles de compétition parfaite

::: notes
Les individus votent *avec leurs pieds* : en déménageant

Nombreuses extensions développées au fil du temps

Hypothèses contraignantes
:::

## Interactions stratégiques

-   Théorie des jeux
-   Interactions entre les décisions de taxation
    -   En plus des caractéristiques économiques, démographiques et politiques, présence d'interaction [@case1993]
    -   Information complète ou incomplète
-   Nombre réduit de juridictions
-   Spill over (positif ou négatif)
-   Yardstick competition
-   Mobilité des agents / du capital

::: notes
**Spill over**: Externalités positives ou négatives pour les voisins

**Yardstick competiton**: Comparaison avec les voisins, contrainte politiques de voteurs

**Mobilité**: La base de taxation se déplace en fonction des différents taux de taxe
:::

## Modélisation économétrique

Interactions stratégiques - corrélation entre les individus

-   Problème d'endogénéité
-   Économétrie spatiale

Modélisation de la variable de taux (continue ou censurée)

::: notes
**interactions**: Modèles économétriques standard assument généralement iid (indép. des individus)

**Censure**: Jamais négatif, contrainte légales exogènes (ex: réglementation fédérale)
:::

## Question de recherche

Estimation des effets d'interactions dans un jeu simultané de compétition fiscale par une approche bayésienne

-   Taux de taxation
-   Municipalité de Caroline du Nord (2012)

::: notes
Basé sur: Tobit models with social interactions: Complete c. incomplete information (Yang et al. 2018)
:::

# Corpus méthodologique

## Modélisation

Économétrie spatiale: permet des interactions dans les chocs, la variable endogène, etc. [@arbia2024]

-   "Spill over" des externalités
-   Déplacement de la base fiscale
-   Yardstick competition

$$y=\lambda Wy + X\beta + u, \quad u = \rho Wu+\varepsilon$$


## Mesurer les interactions

Estimation de l'effet d'interactions sur les dépenses à l'aide de lag spatial[@case1993]

Choix du modèle selon le type de compétition [@bordignon2003]:

-   **SEM**: *Yardstick competition*
-   **SAR**: *Mobilité de l'assiette fiscale*

::: notes
**SEM**: Compétition associée aux variables inobservées (termes d'erreur)

**SAR**: Compétition directement liée à la variable endogène

**Lyytikäinen**: garde uniquement municipalité par lesquelles taux minimum pas contrainte mordante, choc exogène au taux minimum
:::

## Solution de coin

Politiques fiscales limitées avec interactions. Application aux taxes locales sur les véhicules [@porto2013]:

-   Approche bayésienne - Variable censurée
-   Tobit avec lag spatio-temporel
-   Modèle de survie

::: notes
**Bayésien censurée**: choix du taux influencé par taux désiré des voisins et non taux censuré/appliqué (représente moins bien solution coin)

**Tobit lag spatio-temporel**: $\tau_{-it-1}^* = x'_{it}\beta + \rho\tau_{it-1} + \varepsilon_{it},\quad \tau_{it-1} = \sum_{j=1}^N w_{ij}\tau_{jt-1}$

**Modèle de survie**: Probabilité d'atteindre la limite
:::

## Solution de coin et structure d'information

Modèles Tobit avec effet spatial [@qu2012]

-   Tobit SLM simultané
-   Tobit SLM latent

Structure d'information [@yang2018]

-   Complète c. incomplète
-   Variable censurée

::: notes
**Tobit**: Variables fiscales généralement contraintes (ex: taux de taxe) Un SLM est un type de SAR.

**SLM simultané**: Comportement affecté par l'outcome réalisé/observé

**SLM latent**: Interactions entre variables latente au lieu d'outcome réel
:::

# Corpus thématique

## Modèles Tiebout

-   Tiebout (1956)
    -   Littérature test nombreuses hypothèses et implications
    -   Revue de littérature empirique: résultats assez mixtes [@dowding1994]
-   Critiqué pour ses hypothèses très exigeantes[@bewley1981]

::: notes
Littérature riche, mais peu concentrée sur la compétition sur le taux de taxe.

Test de nombreuses hypothèses et implications du modèle, résultats assez mixtes.

Modèle utile, mais sérieuses limitations.
:::

## Interactions

-   Effet positif et important de l'interactions dans les dépenses des états américains [@case1993]
-   Séparation des effets *yardstick* et *spill over* [@bordignon2003] (Italie)
    -   Incertitude politique, interactions positives
-   Interactions et politique [@delgado2015]
-   Pas de preuve solide d'interdépendance dans les municipalités finlandaises [@lyytikäinen2012]

::: notes
Littérature tend à démontrer la présence d'interactions, mais reste de l'incertitude.

**Bordignon** : Données de taxes sur les propriétés en Italie

**Delgado** : Taxes sur propriétés et vehicules

**Lyytikäinen** : taxes sur propriété, manque preuve peut venir faible importance de la taxe

L'ampleur de l'effet est beaucoup moins clair.
:::

## Interactions et solution de coin

Estimation des effets d'interaction à l'aide de modèles spatiaux censurés [@porto2013]

-   Variable endogène observée des voisins significative et importante (lag spatio-temporel)
-   Variable latente représente mal une solution de coin

Équilibre de Nash: information complète [@yang2018]

-   SAR Tobit (simultané)
-   Information incomplète rejetée c. information complète

## Contribution thématique

-   Améliorer la compréhension du processus d'interactions dans les politiques fiscales des juridictions locales sous la forme d'un équilibre de Nash

## Contribution méthodologique

-   Peu de méthodes bayésiennes dans la littérature
    -   L'approche bayésienne permet d'approcher différement et de manière plus intuitive les résultats
-   Diversification des approches
    -   Approche structurelle peu présente

## References
